# Generated by Django 6.0.6 on 2026-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
