# Generated by Django 6.0.6 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0002_document_email_document_name_document_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
