# Generated by Django 6.0.6 on 2026-06-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0006_document_email_document_name_document_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='document',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summary',
        ),
        migrations.AddField(
            model_name='document',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
