# Generated by Django 6.0.6 on 2026-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0007_remove_document_email_remove_document_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='front_file',
        ),
        migrations.AddField(
            model_name='document',
            name='back_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
