# Generated by Django 6.0.6 on 2026-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0008_rename_file_document_front_file_document_back_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='back_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='front_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
