# Generated by Django 6.0.6 on 2026-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0009_document_back_text_document_front_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
